export const dummyInsights = [
  {
    slug: 'understanding-pe-ratio',
    title: 'Understanding P/E Ratio: A Key Metric for Value Investing',
    author: 'Jane Doe',
    date: '2023-05-15',
    image: 'https://picsum.photos/800/400?random=1', // Dummy image URL
    excerpt:
      'Learn how the Price-to-Earnings ratio can help you identify undervalued stocks.',
    content:
      "<p>The Price-to-Earnings (P/E) ratio is a fundamental metric used by investors to assess the valuation of a company's stock...</p>",
    category: 'fundamental',
  },
  {
    slug: 'technical-analysis-basics',
    title: 'Technical Analysis 101: Reading Chart Patterns',
    author: 'John Smith',
    date: '2023-05-20',
    image: 'https://picsum.photos/800/400?random=2', // Dummy image URL
    excerpt:
      'Discover the basics of technical analysis and how to identify common chart patterns.',
    content:
      '<p>Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity...</p>',
    category: 'technical',
  },
  // Add more dummy insights as needed
];

export const dummyCourses = [
  {
    id: 'stock-market-basics',
    title: 'Stock Market Basics',
    instructor: 'Jane Doe',
    thumbnail: 'https://picsum.photos/800/400?random=3',
    price: 99.99,
    level: 'beginner',
    description:
      'Learn the fundamentals of stock market investing in this comprehensive course for beginners.',
    syllabus: [
      'Introduction to the Stock Market',
      'Understanding Stock Prices and Valuation',
      'Building a Diversified Portfolio',
      'Risk Management Strategies',
      'Reading Financial Statements',
    ],
    duration: '4 weeks',
  },
  {
    id: 'technical-analysis-mastery',
    title: 'Technical Analysis Mastery',
    instructor: 'John Smith',
    thumbnail: 'https://picsum.photos/800/400?random=4',
    price: 149.99,
    level: 'intermediate',
    description:
      'Master the art of technical analysis and chart reading to make informed trading decisions.',
    syllabus: [
      'Candlestick Patterns',
      'Trend Analysis',
      'Support and Resistance Levels',
      'Moving Averages and Indicators',
      'Trading Strategies and Backtesting',
    ],
    duration: '6 weeks',
  },
  // Add more dummy courses as needed
];
